version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: nestuser
      POSTGRES_PASSWORD: nestpass
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  nestapp:
    build: .
    container_name: nest_app
    restart: always
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: nestuser
      DATABASE_PASSWORD: nestpass
      DATABASE_NAME: taskdb
volumes:
  pgdata: